default_install_hook_types:
- commit-msg
- pre-commit
default_stages:
- commit
- manual
fail_fast: true
repos:
- hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-xml
  - id: check-yaml
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.0
